language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
#  - "pypy"

install:
  - sudo apt-get -qq install libfreetype6-dev liblcms2-dev libwebp-dev libffi-dev
  - pip install 'docopt >= 0.5'
  - pip install git+git://github.com/ojii/pymaging.git#egg=pymaging
  - pip install 'Pillow >= 2.0'
  - pip install packbits
  - python setup.py install

# command to run tests, e.g. python setup.py test
script: py.test
